### ISSUE TITLE
Past Years

### ISSUE THREAD

**Issue by thebioengineer** [pdxrconf/pdxrconf.github.io#44]
I had someone reach out to me though asking about how to link to past presentations. It looks like with the update (which looks great), some of the old links got blown up. Specifically, the links to 'agendas', which I think then had links to the slides.
https://cascadiarconf.com/years/

If there is a way to recover them, or maybe remove the references it might be a good idea.

**Comment by datalorax** [comment]
Hi Ellis,

I'm not sure on the best way to approach this. The repo is pretty messy, which makes it fairly difficult. Maybe @apreshill or @brendanhcullen have ideas?

**Comment by thebioengineer** [comment]
I just went into the history of the repo and pulled the raw link for the request. So no need for an immediate resolution. 

One solution would to have a "past presentations" page that had everything. But that would take some curation time.

**Comment by datalorax** [comment]
Yeah I think the time commitment part is probably the primary concern for everyone. It would be good to have a more systematic solution that we can continue to use in the coming years, but I for sure don't have the time to be able to devote to it right now, unfortunately.

**Comment by brendanhcullen** [comment]
@thebioengineer, thanks for pointing that out! I agree it would be nice to have past materials be more organized and accessible. If all of the previous materials exist (or are at least linked to) somewhere in the repo, I can take a stab at organizing them and re-vamping the `Years` page. This is a busy week for me, so it might be a few days. 

One question -- I'm assuming what people mostly care about is accessing the speaker bios, talks and slides (if/when those are available)? Would it be sufficient to just have that information rather than old flyers, agendas, etc?

Also, were the 2019 talks recorded? I can't seem to find those anywhere.

**Comment by thebioengineer** [comment]
@brendanhcullen We did attempt to record them. If I remember correctly the quality was not good so we didn't post them. It was a last minute thing since the venue did not have recording tools so we didn't really have a good setup.

**Comment by sckott** [comment]
We have a few recordings of the first two years on youtube https://www.youtube.com/channel/UCbIKQLftgJYFM5tlPxnbXAg/videos - also not great quality. There's some more videos on my local hard drive I haven't got around to editing too.

**Comment by brendanhcullen** [comment]
Great, thanks to you both. I'll put together whatever I can find in the repo and then maybe reach out to see if anyone has recordings/slides that I wasn't able to find.

**Comment by k8hertweck** [comment]
Narrowing this issue down to address only fixing broken links associated with previous years. Reorganization of the site in general will be addressed by #62

**Comment by kdillmcfarland** [comment]
All agenda and video links have been updated in #116
